language: cpp

compiler:
  - gcc
  - clang

install:
  # g++4.8.1
  - if [ "$CXX" = "g++"  ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: 
  - $CXX --version
  - cmake . 
  - make clang-format && make clang-tidy && make && ./main

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake 
      - libyajl-dev
      - libxml2-dev
      - gcc-4.8
      - g++-4.8
      - clang

sudo: false
