language: cpp

compiler:
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++"  ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++"  ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++"  ]; then export CXX="g++-4.8"; fi


script: 
  - $CXX --version
  - cmake . 
  - make
  - ./main

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - gcc-4.8
      - g++-4.8
